### ISSUE TITLE
Admin interface missing

### ISSUE THREAD

**Issue by ghost** [icos-urenio/virtual-city-market#1]
Υπάρχει περιβάλλον διαχειριστή ή δεν έχει υλοποιηθεί ακόμη; 
Δεν δίνεται κάποια περιγραφή αλλά αναλύοντας τον κώδικα βλέπω πως πηγαίνοντας στη διεύθυνση /admin υπάρχει το interface εισόδου (η σύνδεση των χρηστών). 
Με βάση τον πίνακα των χρηστών από τη βάση γίνεται η ταυτοποίηση αλλά μετά τίποτα.
Ευχαριστώ για το χρόνο. Συνεχίστε την καλή δουλειά.

**Comment by dmitzias** [comment]
Η έκδοση που είναι ανεβασμένη στο github είναι πολύ αρχική. Μέσα στον Μάρτιο θα ανεβάσουμε μια νέα έκδοση με όλα τα χαρακτηριστικά.

**Comment by lmak** [comment]
Προστέθηκε το περιβάλλον διαχειριστή στην τελευταία έκδοση.
