### ISSUE TITLE
Admin user

### ISSUE THREAD

**Issue by 2des** [icos-urenio/virtual-city-market#2]
Hello, great program,

how can I update or edit otther users Market as Administrator? Its they a way to aprove the user market registration?

Thank you.
Best regards
2Des

**Comment by 2des** [comment]
I need some help here to:

define('SUPPORT_EMAIL', 'support@localhost'); // Used in email templates
    define('MARKET_SMTP_HOST', 'localhost'); // Outgoing server
    define('MARKET_SMTP_FROM', 'noreply@localhost'); // Return path
    define('MARKET_SMTP_FROM_NAME', 'Virtual city market');
    //define('MARKET_SMTP_USER', '');
    //define('MARKET_SMTP_PASS', '');

I wold like to use Google Apps SMTP!

Thank you.
Best regards
2Des

**Comment by dmitzias** [comment]
try

define('MARKET_SMTP_HOST', 'ssl://smtp.gmail.com:465');
define('MARKET_SMTP_USER', 'email@yourdomain.com');
define('MARKET_SMTP_PASS', 'yourpass');

Change "email@yourdomain.com" and "yourpass" with your account details.
