### ISSUE TITLE
Error when i try to register new user

### ISSUE THREAD

**Issue by b2bviet** [icos-urenio/virtual-city-market#3]
Dear sir,

i try your viryual city market script, but when i register a new user, database does not insert any new record in market_user table.

Can you help me fix this error

**Comment by dmitzias** [comment]
Normally when a new user is registered the following message should be shown:
"Your account was created successfully but is not activated yet. We have send a confirmation message to your email address. Please read it and follow the instructions to activate your account."
Do you see this message?

**Comment by b2bviet** [comment]
Yes, i see this message, but when i click the link in comfirmation email, the system show error.

i check databse, and i see no new record add to market_user table

**Comment by b2bviet** [comment]
You can try my website www.econgty.net

**Comment by dmitzias** [comment]
There were some missing fields in the market_user table. Run the following SQL against your database to correct the error:

ALTER TABLE `market_user`
ADD `reset_password` VARCHAR( 16 ) NOT NULL AFTER `user_email` ,
ADD `reset_password_tstamp` DATETIME NOT NULL AFTER `reset_password` ,
ADD `activate_account` VARCHAR( 16 ) NOT NULL AFTER `reset_password_tstamp` ,
ADD `activate_account_tstamp` DATETIME NOT NULL AFTER `activate_account`

**Comment by b2bviet** [comment]
How i can give up pin code when some user change to local business? i do not know how i can fill pin code for local business.

**Comment by dmitzias** [comment]
Pin codes are stored in the database in the "directory" table

**Comment by b2bviet** [comment]
I also put 123456 for pin code, but the system inform me error

**Comment by dmitzias** [comment]
The pin should be unique for each store.
The pin code 123456 is assigned to store id 1 which is already assigned to market user id 2 (login: business, pass: business)

**Comment by b2bviet** [comment]
I want to remove require pin code in your script, can you help me some files i can change code.

Another thing, i would like to expand the code for country (not a city), but, i do not know the main step i can change your code, may you help me some guide

Best regards,

**Comment by dmitzias** [comment]
1.
The PIN code is used in:
- user registration (templates/account/register.tpl)
- account settings (templates/account/settings/business)

to link a _new_ business account to a _pre-existent_ business directory entry.

You must provide your own code if you want a business user to be able to create a new business directory entry.

2.
There is no restriction to a particular city. You can already define a different city for each business directory entry. 

If you need to enter cities in different countries then you should start by adding a "country" field in directory_ml table and alter the templates where "city" is now present. For example: (directory|marketplace|offers|reviews)/index.tpl, (marketplace|offers)/show.tpl, templates/account/settings/business

**Comment by b2bviet** [comment]
Thank for your reply
Best regards
